const KEY='crs_data_v1', AUTH='crs_auth_v1';
const seed={clients:[],designers:[],clientPayments:[],designerPayments:[],settings:{currency:'CLP'}};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||seed; let page='dashboard';
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(data))} function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function monthDates(start,months=12){let d=new Date(start+'T12:00:00'), out=[];for(let i=0;i<months;i++){let x=new Date(d.getFullYear(),d.getMonth()+i,Math.min(d.getDate(),new Date(d.getFullYear(),d.getMonth()+i+1,0).getDate()),12);out.push(x.toISOString().slice(0,10))}return out}
function syncPayments(){data.clients.forEach(c=>{monthDates(c.startDate,12).forEach(date=>{let id=c.id+'_'+date;if(!data.clientPayments.some(p=>p.id===id))data.clientPayments.push({id,clientId:c.id,dueDate:date,amount:+c.monthlyPrice||0,status:'pending',paidDate:'',method:''})})});save()}
function wa(phone,msg){let p=String(phone||'').replace(/\D/g,''); if(!p)return alert('Agrega el número con código de país.'); location.href='https://wa.me/'+p+'?text='+encodeURIComponent(msg)}
function render(){syncPayments(); const root=document.getElementById('app'); if(!localStorage.getItem(AUTH)){root.innerHTML=login();bindLogin();return} root.innerHTML=layout();bind();}
function login(){return `<div class="login"><div class="login-card"><img class="login-logo" src="icons/logo.png"><h1>Control de redes sociales</h1><p class="muted">Gestión privada de clientes, pagos y diseñadores</p><div class="field"><label>Contraseña</label><input id="pw" type="password" placeholder="Ingresa tu contraseña"></div><button class="btn primary" id="loginBtn">Entrar</button><p class="small muted">Primera vez: usa la contraseña que quieras para crear tu acceso.</p></div></div>`}
function bindLogin(){document.getElementById('loginBtn').onclick=()=>{let p=document.getElementById('pw').value;if(!p)return alert('Escribe una contraseña.');localStorage.setItem(AUTH,btoa(p));render()}}
function layout(){return `<div class="app-shell"><header class="topbar"><div class="brand"><img src="icons/logo.png"><strong>Control de redes sociales</strong></div><button class="logout" id="logout">Cerrar sesión</button></header><main class="content"><nav class="nav">${['dashboard','clientes','diseñadores','finanzas'].map(x=>`<button class="${page===x?'active':''}" data-page="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</nav>${page==='dashboard'?dashboard():page==='clientes'?clients():page==='diseñadores'?designers():finance()}</main></div>`}
function dashboard(){let now=new Date().toISOString().slice(0,10), rev=data.clients.reduce((s,c)=>s+(+c.monthlyPrice||0),0), cost=data.clients.reduce((s,c)=>s+(+c.designerPrice||0),0), due=data.clientPayments.filter(p=>p.status!=='paid'&&p.dueDate<=now).length;return `<div class="section-head"><h2>Resumen</h2><button class="btn secondary" id="export">Exportar respaldo</button></div><div class="grid"><div class="card"><span class="muted">Ingresos mensuales</span><div class="metric">${money(rev)}</div></div><div class="card"><span class="muted">Costos diseñadores</span><div class="metric">${money(cost)}</div></div><div class="card"><span class="muted">Margen mensual</span><div class="metric">${money(rev-cost)}</div></div><div class="card"><span class="muted">Cobros pendientes</span><div class="metric">${due}</div></div></div><div class="section-head"><h2>Próximos cobros</h2></div>${paymentTable(data.clientPayments.filter(p=>p.status!=='paid').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,8))}`}
function status(p){let t=new Date().toISOString().slice(0,10);return p.status==='paid'?'paid':p.dueDate<t?'overdue':'pending'}
function paymentTable(ps){if(!ps.length)return `<div class="card empty">No hay cobros pendientes.</div>`;return `<div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Vence</th><th>Monto</th><th>Estado</th><th></th></tr></thead><tbody>${ps.map(p=>{let c=data.clients.find(x=>x.id===p.clientId);let st=status(p);return `<tr><td>${esc(c?.name||'—')}</td><td>${p.dueDate}</td><td>${money(p.amount)}</td><td><span class="badge ${st}">${st==='overdue'?'Vencido':'Pendiente'}</span></td><td><button class="btn whatsapp" data-wa="${p.clientId}">Cobrar por WhatsApp</button></td></tr>`}).join('')}</tbody></table></div>`}
function clients(){return `<div class="section-head"><h2>Clientes</h2><button class="btn primary" id="newClient">+ Nuevo cliente</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Cliente</th><th>Redes incluidas</th><th>Mensualidad</th><th>Diseñador</th><th>Estado</th><th></th></tr></thead><tbody>${data.clients.map(c=>{let d=data.designers.find(x=>x.id===c.designerId);return `<tr><td><b>${esc(c.name)}</b><br><span class="muted">${esc(c.phone)}</span></td><td>${esc(c.networks.join(', '))}</td><td>${money(c.monthlyPrice)}</td><td>${esc(d?.name||'Sin asignar')}</td><td>${c.active?'Activo':'Inactivo'}</td><td class="actions"><button class="btn secondary" data-edit="${c.id}">Editar</button><button class="btn whatsapp" data-wa="${c.id}">WhatsApp</button></td></tr>`}).join('')||`<tr><td colspan="6" class="empty">Todavía no tienes clientes.</td></tr>`}</tbody></table></div>`}
function designers(){return `<div class="section-head"><h2>Diseñadores</h2><button class="btn primary" id="newDesigner">+ Nuevo diseñador</button></div><div class="grid">${data.designers.map(d=>`<div class="card"><b>${esc(d.name)}</b><p class="muted">${esc(d.phone||'Sin teléfono')}</p><div class="metric">${data.clients.filter(c=>c.designerId===d.id).length}</div><span class="muted">clientes asignados</span></div>`).join('')||'<div class="card empty">No hay diseñadores registrados.</div>'}</div>`}
function finance(){let paid=data.clientPayments.filter(p=>p.status==='paid').reduce((s,p)=>s+p.amount,0), pending=data.clientPayments.filter(p=>p.status!=='paid').reduce((s,p)=>s+p.amount,0), dp=data.designerPayments.reduce((s,p)=>s+(+p.amount||0),0);return `<div class="section-head"><h2>Finanzas</h2><button class="btn secondary" id="export">Exportar respaldo</button></div><div class="grid"><div class="card"><span class="muted">Cobrado</span><div class="metric">${money(paid)}</div></div><div class="card"><span class="muted">Por cobrar</span><div class="metric">${money(pending)}</div></div><div class="card"><span class="muted">Pagos diseñadores</span><div class="metric">${money(dp)}</div></div></div><div class="section-head"><h2>Pagos de clientes</h2></div>${paymentTable(data.clientPayments.slice().sort((a,b)=>b.dueDate.localeCompare(a.dueDate)))}`}
function modal(html){let d=document.createElement('div');d.className='modal';d.innerHTML=`<div class="modal-card">${html}</div>`;document.body.appendChild(d);return d}
function clientForm(c){let x=c||{name:'',phone:'',email:'',startDate:new Date().toISOString().slice(0,10),monthlyPrice:'',designerPrice:'',designerId:'',networks:['Instagram','Facebook','TikTok'],active:true,notes:''};let d=modal(`<h2>${c?'Editar':'Nuevo'} cliente</h2><div class="field"><label>Nombre</label><input id="f_name" value="${esc(x.name)}"></div><div class="field"><label>WhatsApp</label><input id="f_phone" value="${esc(x.phone)}" placeholder="Código de país + número"></div><div class="field"><label>Correo</label><input id="f_email" value="${esc(x.email)}"></div><div class="row"><div class="field"><label>Inicio / fecha de cobro</label><input id="f_start" type="date" value="${x.startDate}"></div><div class="field"><label>Mensualidad cliente</label><input id="f_price" type="number" value="${x.monthlyPrice}"></div></div><div class="row"><div class="field"><label>Pago mensual diseñador</label><input id="f_dp" type="number" value="${x.designerPrice}"></div><div class="field"><label>Diseñador</label><select id="f_des"><option value="">Sin asignar</option>${data.designers.map(q=>`<option value="${q.id}" ${q.id===x.designerId?'selected':''}>${esc(q.name)}</option>`).join('')}</select></div></div><div class="field"><label>Redes incluidas</label><div class="actions">${['Instagram','Facebook','TikTok'].map(n=>`<label><input type="checkbox" class="net" value="${n}" ${x.networks.includes(n)?'checked':''}> ${n}</label>`).join('')}</div></div><div class="field"><label>Notas</label><textarea id="f_notes">${esc(x.notes)}</textarea></div><div class="actions"><button class="btn primary" id="saveC">Guardar</button><button class="btn secondary" id="cancel">Cancelar</button></div>`);d.querySelector('#cancel').onclick=()=>d.remove();d.querySelector('#saveC').onclick=()=>{let obj={id:c?.id||uid(),name:document.getElementById('f_name').value,phone:document.getElementById('f_phone').value,email:document.getElementById('f_email').value,startDate:document.getElementById('f_start').value,monthlyPrice:+document.getElementById('f_price').value||0,designerPrice:+document.getElementById('f_dp').value||0,designerId:document.getElementById('f_des').value,networks:[...d.querySelectorAll('.net:checked')].map(e=>e.value),active:true,notes:document.getElementById('f_notes').value};let i=data.clients.findIndex(q=>q.id===obj.id);if(i<0)data.clients.push(obj);else data.clients[i]=obj;save();d.remove();render()}}
function designerForm(){let d=modal(`<h2>Nuevo diseñador</h2><div class="field"><label>Nombre</label><input id="dn"></div><div class="field"><label>WhatsApp</label><input id="dp"></div><div class="actions"><button class="btn primary" id="ds">Guardar</button><button class="btn secondary" id="dc">Cancelar</button></div>`);d.querySelector('#dc').onclick=()=>d.remove();d.querySelector('#ds').onclick=()=>{data.designers.push({id:uid(),name:d.querySelector('#dn').value,phone:d.querySelector('#dp').value});save();d.remove();render()}}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.getElementById('logout')?.addEventListener('click',()=>{localStorage.removeItem(AUTH);render()});document.getElementById('newClient')?.addEventListener('click',()=>clientForm());document.getElementById('newDesigner')?.addEventListener('click',designerForm);document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>clientForm(data.clients.find(c=>c.id===b.dataset.edit)));document.querySelectorAll('[data-wa]').forEach(b=>b.onclick=()=>{let c=data.clients.find(x=>x.id===b.dataset.wa);let p=data.clientPayments.filter(x=>x.clientId===c.id&&x.status!=='paid').sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];wa(c.phone,`Hola ${c.name}, te escribo de AC Soluciones. ${p?`Tenemos pendiente tu pago de ${money(p.amount)} con vencimiento ${p.dueDate}.`: 'Quería ponerme en contacto contigo respecto a tu servicio mensual.'} ¿Me confirmas por favor?`)});document.querySelectorAll('#export').forEach(b=>b.onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='respaldo-control-redes-sociales.json';a.click()})}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{})); render();
