const KEY='crs_data_v2', AUTH='crs_auth_v1';
const seed={clients:[],designers:[],clientPayments:[],designerPayments:[],settings:{currency:'CLP'}};
let data=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('crs_data_v1')||'null')||structuredClone(seed);
let page='dashboard';
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function dateForMonth(year,month,day){return new Date(year,month+1,Math.min(day,new Date(year,month+1,0).getDate()),12).toISOString().slice(0,10)}
function monthKey(date){return String(date).slice(0,7)}
function addMonths(dateString,n){let d=new Date(dateString+'T12:00:00'); return dateForMonth(d.getFullYear(),d.getMonth()+n,d.getDate())}
function initialDueDate(c){return c.startDate||today()}
function save(){localStorage.setItem(KEY,JSON.stringify(data));localStorage.setItem('crs_data_v1',JSON.stringify(data))}
function normalize(){
  data.clients ||= []; data.designers ||= []; data.clientPayments ||= []; data.designerPayments ||= [];
  data.clients.forEach(c=>{c.networks ||= ['Instagram','Facebook','TikTok']; c.active=c.active!==false; c.monthlyPrice=+c.monthlyPrice||0; c.designerPrice=+c.designerPrice||0});
  data.designers.forEach(d=>{d.phone ||= ''});
  // Only create payment records through the current month + the next month. No 12-month future backlog.
  data.clients.forEach(c=>{
    if(!c.startDate)return;
    const start=new Date(c.startDate+'T12:00:00'); const now=new Date();
    const first=new Date(start.getFullYear(),start.getMonth(),1,12); const end=new Date(now.getFullYear(),now.getMonth()+1,1,12);
    for(let cur=new Date(first);cur<=end;cur.setMonth(cur.getMonth()+1)){
      const due=dateForMonth(cur.getFullYear(),cur.getMonth(),start.getDate());
      if(due<c.startDate)continue;
      const id=c.id+'_'+due;
      if(!data.clientPayments.some(p=>p.id===id)) data.clientPayments.push({id,clientId:c.id,dueDate:due,amount:c.monthlyPrice,status:'pending',paidDate:'',method:''});
    }
  });
  // Remove future payment records beyond next month so the interface does not pre-create months.
  const limit=new Date(); limit.setMonth(limit.getMonth()+1,1); limit.setHours(0,0,0,0);
  data.clientPayments=data.clientPayments.filter(p=>{let d=new Date(p.dueDate+'T12:00:00'); return d<=limit || p.status==='paid'});
  data.clientPayments.forEach(p=>{let c=data.clients.find(x=>x.id===p.clientId); if(c)p.amount=+c.monthlyPrice||p.amount||0});
  save();
}
function paymentState(p){if(p.status==='paid')return 'paid'; return p.dueDate<today()?'overdue':'pending'}
function clientPayments(c){return data.clientPayments.filter(p=>p.clientId===c.id).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))}
function outstanding(c){return clientPayments(c).filter(p=>paymentState(p)!=='paid').reduce((s,p)=>s+p.amount,0)}
function overdueCount(c){return clientPayments(c).filter(p=>paymentState(p)==='overdue').length}
function nextDue(c){return clientPayments(c).filter(p=>paymentState(p)!=='paid').sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0] || clientPayments(c).sort((a,b)=>b.dueDate.localeCompare(a.dueDate))[0]}
function wa(phone,msg){let p=String(phone||'').replace(/\D/g,'');if(!p)return alert('Agrega el número con código de país.');location.href='https://wa.me/'+p+'?text='+encodeURIComponent(msg)}
function render(){normalize();const root=document.getElementById('app');if(!localStorage.getItem(AUTH)){root.innerHTML=login();bindLogin();return}root.innerHTML=layout();bind()}
function login(){return `<div class="login"><div class="login-card"><img class="login-logo" src="icons/logo.png"><h1>Control de redes sociales</h1><p class="muted">Gestión privada de clientes, pagos y diseñadores</p><div class="field"><label>Contraseña</label><input id="pw" type="password" placeholder="Ingresa tu contraseña"></div><button class="btn primary" id="loginBtn">Entrar</button><p class="small muted">Primera vez: usa la contraseña que quieras para crear tu acceso.</p></div></div>`}
function bindLogin(){document.getElementById('loginBtn').onclick=()=>{let p=document.getElementById('pw').value;if(!p)return alert('Escribe una contraseña.');localStorage.setItem(AUTH,btoa(p));render()}}
function layout(){return `<div class="app-shell"><header class="topbar"><div class="brand"><img src="icons/logo.png"><strong>Control de redes sociales</strong></div><button class="logout" id="logout">Cerrar sesión</button></header><main class="content"><nav class="nav">${['dashboard','clientes','diseñadores','finanzas'].map(x=>`<button class="${page===x?'active':''}" data-page="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</nav>${page==='dashboard'?dashboard():page==='clientes'?clients():page==='diseñadores'?designers():finance()}</main></div>`}
function dashboard(){
 const active=data.clients.filter(c=>c.active); const rev=active.reduce((s,c)=>s+(+c.monthlyPrice||0),0); const cost=active.reduce((s,c)=>s+(+c.designerPrice||0),0);
 const pending=active.reduce((s,c)=>s+outstanding(c),0); const overdue=active.reduce((s,c)=>s+overdueCount(c),0);
 const next=active.map(c=>({c,p:nextDue(c)})).filter(x=>x.p&&paymentState(x.p)!=='paid').sort((a,b)=>a.p.dueDate.localeCompare(b.p.dueDate)).slice(0,6);
 return `<div class="section-head"><div><h2>Resumen</h2><p class="muted compact-sub">Vista general de tus cuentas, diseñadores y cobros.</p></div><button class="btn secondary" id="export">Exportar respaldo</button></div>
 <div class="grid dashboard-grid"><div class="card stat-card"><span class="muted">Cuentas de redes</span><div class="metric">${active.length}</div><span class="mini-label">activas</span></div><div class="card stat-card"><span class="muted">Diseñadores</span><div class="metric">${data.designers.length}</div><span class="mini-label">registrados</span></div><div class="card stat-card"><span class="muted">Ingresos mensuales</span><div class="metric">${money(rev)}</div></div><div class="card stat-card"><span class="muted">Por cobrar</span><div class="metric">${money(pending)}</div><span class="mini-label">${overdue} ${overdue===1?'mes vencido':'meses vencidos'}</span></div></div>
 <div class="section-head"><h2>Próximos cobros</h2><span class="muted">Solo se muestra el siguiente cobro de cada cuenta.</span></div>${next.length?`<div class="compact-list">${next.map(({c,p})=>`<div class="compact-row"><div class="avatar">${esc(c.name).charAt(0).toUpperCase()}</div><div class="compact-main"><b>${esc(c.name)}</b><span>${p.dueDate} · ${money(outstanding(c))}${overdueCount(c)>1?` · ${overdueCount(c)} meses pendientes`:''}</span></div><span class="badge ${paymentState(p)}">${paymentState(p)==='overdue'?'Vencido':'Pendiente'}</span><button class="btn whatsapp small-btn" data-wa="${c.id}">WhatsApp</button></div>`).join('')}</div>`:`<div class="card empty">No hay cobros pendientes.</div>`}`}
function clients(){return `<div class="section-head"><div><h2>Clientes</h2><p class="muted compact-sub">Cada cliente representa una cuenta global de redes sociales.</p></div><button class="btn primary" id="newClient">+ Nuevo cliente</button></div><div class="client-list">${data.clients.map(c=>{let late=overdueCount(c),st=late?'overdue':(c.active?'active':'inactive');return `<button class="client-card" data-view-client="${c.id}"><div class="avatar client-avatar">${esc(c.name).charAt(0).toUpperCase()}</div><div class="client-card-main"><b>${esc(c.name)}</b><span>${money(c.monthlyPrice)} mensual</span></div><span class="client-status ${st}"><i></i>${late?`${late} ${late===1?'mes vencido':'meses vencidos'}`:(c.active?'Activo':'Inactivo')}</span><span class="client-arrow">›</span></button>`}).join('')||`<div class="card empty">Todavía no tienes clientes.</div>`}</div>`}
function designers(){return `<div class="section-head"><div><h2>Diseñadores</h2><p class="muted compact-sub">Edita diseñadores y revisa rápidamente sus clientes asignados.</p></div><button class="btn primary" id="newDesigner">+ Nuevo diseñador</button></div><div class="designer-list">${data.designers.map(d=>{let cs=data.clients.filter(c=>c.designerId===d.id);return `<div class="designer-card"><div class="designer-top"><div class="avatar designer-avatar">${esc(d.name).charAt(0).toUpperCase()}</div><div class="compact-main"><b>${esc(d.name)}</b><span>${cs.length} ${cs.length===1?'cliente':'clientes'} asignados</span></div><button class="btn secondary" data-edit-designer="${d.id}">Editar</button></div><div class="assigned-clients">${cs.length?cs.map(c=>`<button class="client-chip" data-edit="${c.id}">${esc(c.name)}</button>`).join(''):'<span class="muted">Sin clientes asignados</span>'}</div></div>`}).join('')||'<div class="card empty">No hay diseñadores registrados.</div>'}</div>`}
function finance(){let paid=data.clientPayments.filter(p=>p.status==='paid').reduce((s,p)=>s+p.amount,0),pending=data.clientPayments.filter(p=>paymentState(p)!=='paid').reduce((s,p)=>s+p.amount,0),dp=data.designerPayments.reduce((s,p)=>s+(+p.amount||0),0);return `<div class="section-head"><h2>Finanzas</h2><button class="btn secondary" id="export">Exportar respaldo</button></div><div class="grid"><div class="card"><span class="muted">Cobrado</span><div class="metric">${money(paid)}</div></div><div class="card"><span class="muted">Por cobrar</span><div class="metric">${money(pending)}</div></div><div class="card"><span class="muted">Pagos diseñadores</span><div class="metric">${money(dp)}</div></div><div class="card"><span class="muted">Cuentas activas</span><div class="metric">${data.clients.filter(c=>c.active).length}</div></div></div><div class="section-head"><h2>Pagos de clientes</h2><span class="muted">Historial y meses pendientes por cuenta.</span></div>${paymentTable(data.clientPayments.slice().sort((a,b)=>b.dueDate.localeCompare(a.dueDate)))}`}
function paymentTable(ps){if(!ps.length)return `<div class="card empty">No hay pagos registrados.</div>`;return `<div class="table-wrap"><table class="table compact-table"><thead><tr><th>Cliente</th><th>Mes</th><th>Monto</th><th>Estado</th><th></th></tr></thead><tbody>${ps.map(p=>{let c=data.clients.find(x=>x.id===p.clientId);if(!c)return '';let st=paymentState(p);return `<tr><td><b>${esc(c.name)}</b></td><td>${p.dueDate}</td><td>${money(p.amount)}</td><td><span class="badge ${st}">${st==='overdue'?'Vencido':st==='paid'?'Pagado':'Pendiente'}</span></td><td>${st==='paid'?`<span class="muted">Pagado ${p.paidDate||''}</span>`:`<button class="btn primary" data-pay-one="${p.id}">Registrar pago</button>`}</td></tr>`}).join('')}</tbody></table></div>`}
function modal(html){let d=document.createElement('div');d.className='modal';d.innerHTML=`<div class="modal-card">${html}</div>`;document.body.appendChild(d);return d}

function clientDetail(c){let d=data.designers.find(x=>x.id===c.designerId), ps=clientPayments(c), pending=outstanding(c), late=overdueCount(c);let m=modal(`<div class="modal-head"><div><span class="detail-kicker">Cuenta de redes sociales</span><h2>${esc(c.name)}</h2><p class="muted">${c.active?'Cliente activo':'Cliente inactivo'}</p></div><button class="icon-btn" id="cdx">×</button></div><div class="detail-status ${late?'danger':'good'}"><span class="status-dot ${late?'off':'on'}"></span><b>${late?`${late} ${late===1?'mes vencido':'meses vencidos'}`:(c.active?'Al día':'Inactivo')}</b><span>${pending?` · ${money(pending)} pendiente`:''}</span></div><div class="detail-grid"><div><span>Mensualidad</span><b>${money(c.monthlyPrice)}</b></div><div><span>Diseñador</span><b>${esc(d?.name||'Sin asignar')}</b></div><div><span>Redes asignadas</span><b>${esc((c.networks||[]).join(' · ')||'Sin redes')}</b></div><div><span>Fecha de cobro</span><b>${esc(c.startDate||'Sin fecha')}</b></div><div><span>WhatsApp</span><b>${c.phone?esc(c.phone):'No registrado'}</b></div><div><span>Correo</span><b>${c.email?esc(c.email):'Sin correo'}</b></div></div>${c.notes?`<div class="detail-notes"><span>Notas</span><p>${esc(c.notes)}</p></div>`:''}<div class="detail-actions"><button class="btn primary" id="cdEdit">Editar cliente</button><button class="btn secondary" id="cdPay">Ver pagos</button><button class="btn whatsapp" id="cdWa">WhatsApp</button></div><div class="detail-payments"><div class="detail-section-title"><b>Estado de pagos</b><span>${ps.filter(p=>paymentState(p)==='paid').length} pagados · ${ps.filter(p=>paymentState(p)!=='paid').length} pendientes</span></div>${ps.slice().reverse().map(p=>{let st=paymentState(p);return `<div class="detail-payment-row"><div><b>${esc(p.dueDate)}</b><span>${money(p.amount)}${p.paidDate?` · pagado ${esc(p.paidDate)}`:''}</span></div><span class="badge ${st}">${st==='paid'?'Pagado':st==='overdue'?'Vencido':'Pendiente'}</span></div>`}).join('')||'<span class="muted">No hay pagos registrados.</span>'}</div>`);m.querySelector('#cdx').onclick=()=>m.remove();m.querySelector('#cdEdit').onclick=()=>{m.remove();clientForm(c)};m.querySelector('#cdPay').onclick=()=>{m.remove();paymentHistory(c)};m.querySelector('#cdWa').onclick=()=>{let amount=outstanding(c);wa(c.phone,`Hola ${c.name}, te escribo de AC Soluciones. ${amount?`Tenemos pendiente tu pago de ${money(amount)}${late?` correspondiente a ${late} ${late===1?'mes vencido':'meses vencidos'}`:''}.`:'Quería ponerme en contacto contigo respecto a tu servicio mensual.'} ¿Me confirmas por favor?`)}}
function clientForm(c){let x=c||{name:'',phone:'',email:'',startDate:today(),monthlyPrice:'',designerPrice:'',designerId:'',networks:['Instagram','Facebook','TikTok'],active:true,notes:''};let d=modal(`<div class="modal-head"><div><h2>${c?'Editar':'Nuevo'} cliente</h2><p class="muted">Una cuenta global puede incluir una o varias redes.</p></div><button class="icon-btn" id="cancel">×</button></div><div class="field"><label>Nombre</label><input id="f_name" value="${esc(x.name)}"></div><div class="field"><label>WhatsApp</label><input id="f_phone" value="${esc(x.phone)}" placeholder="Código de país + número"></div><div class="field"><label>Correo</label><input id="f_email" value="${esc(x.email)}"></div><div class="row"><div class="field"><label>Fecha inicial de cobro</label><input id="f_start" type="date" value="${x.startDate}"></div><div class="field"><label>Mensualidad cliente</label><input id="f_price" type="number" value="${x.monthlyPrice}"></div></div><div class="row"><div class="field"><label>Pago mensual diseñador</label><input id="f_dp" type="number" value="${x.designerPrice}"></div><div class="field"><label>Diseñador</label><select id="f_des"><option value="">Sin asignar</option>${data.designers.map(q=>`<option value="${q.id}" ${q.id===x.designerId?'selected':''}>${esc(q.name)}</option>`).join('')}</select></div></div><div class="field"><label>Redes incluidas</label><div class="actions">${['Instagram','Facebook','TikTok'].map(n=>`<label class="check"><input type="checkbox" class="net" value="${n}" ${x.networks.includes(n)?'checked':''}> ${n}</label>`).join('')}</div></div><div class="field"><label>Estado</label><select id="f_active"><option value="true" ${x.active?'selected':''}>Activo</option><option value="false" ${!x.active?'selected':''}>Inactivo</option></select></div><div class="field"><label>Notas</label><textarea id="f_notes">${esc(x.notes)}</textarea></div><div class="actions"><button class="btn primary" id="saveC">Guardar cambios</button><button class="btn secondary" id="cancel2">Cancelar</button></div>`);d.querySelectorAll('#cancel,#cancel2').forEach(b=>b.onclick=()=>d.remove());d.querySelector('#saveC').onclick=()=>{let obj={id:c?.id||uid(),name:d.querySelector('#f_name').value.trim(),phone:d.querySelector('#f_phone').value.trim(),email:d.querySelector('#f_email').value.trim(),startDate:d.querySelector('#f_start').value,monthlyPrice:+d.querySelector('#f_price').value||0,designerPrice:+d.querySelector('#f_dp').value||0,designerId:d.querySelector('#f_des').value,networks:[...d.querySelectorAll('.net:checked')].map(e=>e.value),active:d.querySelector('#f_active').value==='true',notes:d.querySelector('#f_notes').value};if(!obj.name)return alert('Escribe el nombre del cliente.');let i=data.clients.findIndex(q=>q.id===obj.id);if(i<0)data.clients.push(obj);else data.clients[i]=obj;save();d.remove();render()}}
function designerForm(existing){let x=existing||{name:'',phone:'',email:'',notes:''};let d=modal(`<div class="modal-head"><div><h2>${existing?'Editar':'Nuevo'} diseñador</h2><p class="muted">El teléfono queda guardado, pero oculto en la vista principal.</p></div><button class="icon-btn" id="dc">×</button></div><div class="field"><label>Nombre</label><input id="dn" value="${esc(x.name)}"></div><div class="field"><label>WhatsApp</label><input id="dp" value="${esc(x.phone)}"></div><div class="field"><label>Correo</label><input id="de" value="${esc(x.email)}"></div><div class="field"><label>Notas</label><textarea id="do">${esc(x.notes)}</textarea></div><div class="actions"><button class="btn primary" id="ds">Guardar cambios</button><button class="btn secondary" id="dc2">Cancelar</button></div>`);d.querySelectorAll('#dc,#dc2').forEach(b=>b.onclick=()=>d.remove());d.querySelector('#ds').onclick=()=>{let obj={id:existing?.id||uid(),name:d.querySelector('#dn').value.trim(),phone:d.querySelector('#dp').value.trim(),email:d.querySelector('#de').value.trim(),notes:d.querySelector('#do').value};if(!obj.name)return alert('Escribe el nombre del diseñador.');let i=data.designers.findIndex(q=>q.id===obj.id);if(i<0)data.designers.push(obj);else data.designers[i]=obj;save();d.remove();render()}}
function paymentHistory(c){let ps=clientPayments(c);let due=ps.filter(p=>paymentState(p)!=='paid');let d=modal(`<div class="modal-head"><div><h2>Pagos de ${esc(c.name)}</h2><p class="muted">Pendiente actual: <b>${money(outstanding(c))}</b> · ${overdueCount(c)} ${overdueCount(c)===1?'mes vencido':'meses vencidos'}</p></div><button class="icon-btn" id="phx">×</button></div><div class="payment-summary"><div><span class="muted">Meses pendientes</span><b>${due.length}</b></div><div><span class="muted">Total pendiente</span><b>${money(outstanding(c))}</b></div></div><div class="payment-history">${ps.map(p=>{let st=paymentState(p);return `<div class="payment-line"><div><b>${p.dueDate}</b><span>${money(p.amount)}${p.paidDate?' · pagado '+p.paidDate:''}</span></div><span class="badge ${st}">${st==='paid'?'Pagado':st==='overdue'?'Vencido':'Pendiente'}</span>${st!=='paid'?`<button class="btn primary small-btn" data-modal-pay="${p.id}">Registrar pago</button>`:''}</div>`}).join('')}</div>`);d.querySelector('#phx').onclick=()=>d.remove();d.querySelectorAll('[data-modal-pay]').forEach(b=>b.onclick=()=>recordPayment(b.dataset.modalPay,d))}
function recordPayment(paymentId,hostModal){let p=data.clientPayments.find(x=>x.id===paymentId);if(!p)return;let c=data.clients.find(x=>x.id===p.clientId);let d=modal(`<h2>Registrar pago</h2><p class="muted">${esc(c.name)} · ${p.dueDate} · ${money(p.amount)}</p><div class="field"><label>Fecha de pago</label><input id="pd" type="date" value="${today()}"></div><div class="field"><label>Método de pago</label><select id="pm"><option>Transferencia</option><option>Webpay</option><option>Efectivo</option><option>Otro</option></select></div><div class="actions"><button class="btn primary" id="ps">Marcar como pagado</button><button class="btn secondary" id="pc">Cancelar</button></div>`);d.querySelector('#pc').onclick=()=>d.remove();d.querySelector('#ps').onclick=()=>{p.status='paid';p.paidDate=d.querySelector('#pd').value;p.method=d.querySelector('#pm').value;save();d.remove();hostModal.remove();paymentHistory(c);render()}}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.getElementById('logout')?.addEventListener('click',()=>{localStorage.removeItem(AUTH);render()});document.getElementById('newClient')?.addEventListener('click',()=>clientForm());document.getElementById('newDesigner')?.addEventListener('click',()=>designerForm());document.querySelectorAll('[data-view-client]').forEach(b=>b.onclick=()=>clientDetail(data.clients.find(c=>c.id===b.dataset.viewClient)));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>clientForm(data.clients.find(c=>c.id===b.dataset.edit)));document.querySelectorAll('[data-payments]').forEach(b=>b.onclick=()=>paymentHistory(data.clients.find(c=>c.id===b.dataset.payments)));document.querySelectorAll('[data-edit-designer]').forEach(b=>b.onclick=()=>designerForm(data.designers.find(x=>x.id===b.dataset.editDesigner)));document.querySelectorAll('[data-pay-one]').forEach(b=>b.onclick=()=>{let p=data.clientPayments.find(x=>x.id===b.dataset.payOne),c=data.clients.find(x=>x.id===p.clientId);paymentHistory(c)});document.querySelectorAll('[data-wa]').forEach(b=>b.onclick=()=>{let c=data.clients.find(x=>x.id===b.dataset.wa);let p=nextDue(c);let amount=outstanding(c);wa(c.phone,`Hola ${c.name}, te escribo de AC Soluciones. ${amount?`Tenemos pendiente tu pago de ${money(amount)}${overdueCount(c)?` correspondiente a ${overdueCount(c)} ${overdueCount(c)===1?'mes vencido':'meses vencidos'}`:''}.`: 'Quería ponerme en contacto contigo respecto a tu servicio mensual.'} ¿Me confirmas por favor?`)});document.querySelectorAll('#export').forEach(b=>b.onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='respaldo-control-redes-sociales.json';a.click()})}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render();
